name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  google_maps_api:
    path: ../
  logging: ^1.0.1
dev_dependencies:
  pedantic: ^1.11.0
