name: google_maps_api
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  chopper: ^3.0.6
  json_annotation: ^3.1.1

dev_dependencies:
  build_runner: ^1.10.6
  chopper_generator: ^3.0.6
  json_serializable: ^3.5.0
  pedantic: ^1.9.0
  test: ^1.14.4
