name: google_maps_api
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.5
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.5
  pedantic: ^1.11.1
  test: ^1.20.2
