name: google_maps_api
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  chopper_generator: ^4.0.1
  json_serializable: ^4.1.3
  pedantic: ^1.11.0
  test: ^1.17.8
